from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets


class InputJadwal(QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.setFixedSize(683, 384)
    def setupUi(self):
        self.setWindowTitle("Input atau Edit Jadwal")


        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(0, 0, 683, 384))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.judulJadwalBaru = QtWidgets.QLabel(self.frame)
        self.judulJadwalBaru.setGeometry(QtCore.QRect(150, 20, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.judulJadwalBaru.setFont(font)
        self.judulJadwalBaru.setStyleSheet("background-color: rgb(33, 150, 243);border-radius:20px;\n"
"color: rgb(255, 255, 255);")
        self.judulJadwalBaru.setAlignment(QtCore.Qt.AlignCenter)
        self.judulJadwalBaru.setObjectName("judulJadwalBaru")
        self.lblJudul = QtWidgets.QLabel(self.frame)
        self.lblJudul.setGeometry(QtCore.QRect(80, 110, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblJudul.setFont(font)
        self.lblJudul.setObjectName("lblJudul")
        self.lblTanggal = QtWidgets.QLabel(self.frame)
        self.lblTanggal.setGeometry(QtCore.QRect(80, 150, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTanggal.setFont(font)
        self.lblTanggal.setObjectName("lblTanggal")
        self.lblJam = QtWidgets.QLabel(self.frame)
        self.lblJam.setGeometry(QtCore.QRect(80, 190, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblJam.setFont(font)
        self.lblJam.setObjectName("lblJam")
        self.lblKeterangan = QtWidgets.QLabel(self.frame)
        self.lblKeterangan.setGeometry(QtCore.QRect(80, 240, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblKeterangan.setFont(font)
        self.lblKeterangan.setObjectName("lblKeterangan")
        self.inputJudul = QtWidgets.QLineEdit(self.frame)
        self.inputJudul.setGeometry(QtCore.QRect(280, 110, 331, 20))
        self.inputJudul.setObjectName("inputJudul")
        self.inputTanggal = QtWidgets.QLineEdit(self.frame)
        self.inputTanggal.setGeometry(QtCore.QRect(280, 150, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.inputTanggal.setFont(font)
#        self.inputTanggal.setMinimumDate(QtCore.QDate(2021, 7, 12))
#        self.inputTanggal.setTimeSpec(QtCore.Qt.LocalTime)
#        self.inputTanggal.setDate(QtCore.QDate(2021, 7, 13))
        self.inputTanggal.setPlaceholderText("Input tanggal...")
        self.inputTanggal.setObjectName("inputTanggal")
        self.inputJam = QtWidgets.QLineEdit(self.frame)
        self.inputJam.setGeometry(QtCore.QRect(280, 190, 111, 22))
#        self.inputJam.setTime(QtCore.QTime(13, 49, 0))
        self.inputJam.setObjectName("inputJam")
        self.inputJam.setPlaceholderText("Input jam...")
        self.inputKeterangan = QtWidgets.QLineEdit(self.frame)
        self.inputKeterangan.setGeometry(QtCore.QRect(280, 240, 331, 61))
        self.inputKeterangan.setObjectName("inputKeterangan")
        self.btnSimpan = QtWidgets.QToolButton(self.frame)
        self.btnSimpan.setGeometry(QtCore.QRect(490, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSimpan.setFont(font)
        self.btnSimpan.setStyleSheet("border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(74, 79, 74);")
        self.btnSimpan.setObjectName("btnSimpan")
        self.btnBatal = QtWidgets.QToolButton(self.frame)
        self.btnBatal.setGeometry(QtCore.QRect(350, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBatal.setFont(font)
        self.btnBatal.setStyleSheet("border-radius:20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.btnBatal.setObjectName("btnBatal")

        self.judulJadwalBaru.setText("INPUT/EDIT")
        self.lblJudul.setText("Judul                                    : ")
        self.lblTanggal.setText("Tanggal                                :")
        self.lblJam.setText("Jam                                      : ")
        self.lblKeterangan.setText("Keterangan                         : ")
        self.btnSimpan.setText("Simpan")
        self.btnBatal.setText("Batal")

        self.btnSimpan.clicked.connect(self.accept)
        self.btnBatal.clicked.connect(self.reject)


