# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tugas_kisi_uts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        # untuk setting main window nya
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(453, 598)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # code untuk membuat text edit untuk menampung data
        self.untuk_menampung_hasil = QtWidgets.QTextEdit(self.centralwidget)
        self.untuk_menampung_hasil.setGeometry(QtCore.QRect(60, 70, 331, 311))
        self.untuk_menampung_hasil.setObjectName("untuk_menampung_hasil")

        # code untuk bagian judul
        self.judul = QtWidgets.QLabel(self.centralwidget)
        self.judul.setGeometry(QtCore.QRect(110, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setAlignment(QtCore.Qt.AlignCenter)
        self.judul.setObjectName("judul")

        # code untuk setting kolom
        self.kolomNim = QtWidgets.QLineEdit(self.centralwidget)
        self.kolomNim.setGeometry(QtCore.QRect(120, 410, 271, 20))
        self.kolomNim.setObjectName("kolomNim")
        self.kolomNama = QtWidgets.QLineEdit(self.centralwidget)
        self.kolomNama.setGeometry(QtCore.QRect(120, 440, 271, 20))
        self.kolomNama.setObjectName("kolomNama")
        self.kolomJurusan = QtWidgets.QLineEdit(self.centralwidget)
        self.kolomJurusan.setGeometry(QtCore.QRect(120, 470, 271, 20))
        self.kolomJurusan.setObjectName("kolomJurusan")
        self.kolomNoTelpon = QtWidgets.QLineEdit(self.centralwidget)
        self.kolomNoTelpon.setGeometry(QtCore.QRect(120, 500, 271, 20))
        self.kolomNoTelpon.setObjectName("kolomNoTelpon")

        # code untuk edit label
        # label nim
        self.labelNim = QtWidgets.QLabel(self.centralwidget)
        self.labelNim.setGeometry(QtCore.QRect(60, 410, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNim.setFont(font)
        self.labelNim.setObjectName("labelNim")
        # label nama
        self.labelNama = QtWidgets.QLabel(self.centralwidget)
        self.labelNama.setGeometry(QtCore.QRect(60, 440, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNama.setFont(font)
        self.labelNama.setObjectName("labelNama")
        # label jurusan
        self.labelJurusan = QtWidgets.QLabel(self.centralwidget)
        self.labelJurusan.setGeometry(QtCore.QRect(60, 470, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelJurusan.setFont(font)
        self.labelJurusan.setObjectName("labelJurusan")
        # label no.Telp
        self.labelNoTelpon = QtWidgets.QLabel(self.centralwidget)
        self.labelNoTelpon.setGeometry(QtCore.QRect(60, 500, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNoTelpon.setFont(font)
        self.labelNoTelpon.setObjectName("labelNoTelpon")

        # code untuk setting button
        # code button tambah
        self.buttonTambah = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTambah.setGeometry(QtCore.QRect(120, 540, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonTambah.setFont(font)
        self.buttonTambah.setObjectName("buttonTambah")
        # code untuk button edit
        self.buttonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEdit.setGeometry(QtCore.QRect(190, 540, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonEdit.setFont(font)
        self.buttonEdit.setObjectName("buttonEdit")
        # code untuk button clear
        self.buttonClear = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClear.setGeometry(QtCore.QRect(260, 540, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonClear.setFont(font)
        self.buttonClear.setObjectName("buttonClear")
        # code untuk button hapus
        self.buttonHapus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonHapus.setGeometry(QtCore.QRect(330, 540, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonHapus.setFont(font)
        self.buttonHapus.setObjectName("buttonHapus")

        # agar berada di tenga main windownya saat dibuka
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    # fungsi ini digunakan untuk memberi nama pada buttonnya secara tampilan
    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.judul.setText(_translate("mainWindow", "Data Mahasiswa"))
        self.buttonTambah.setText(_translate("mainWindow", "Tambah"))
        self.labelNim.setText(_translate("mainWindow", "Nim"))
        self.labelNama.setText(_translate("mainWindow", "Nama"))
        self.labelJurusan.setText(_translate("mainWindow", "Jurusan"))
        self.labelNoTelpon.setText(_translate("mainWindow", "No. Telp"))
        self.buttonEdit.setText(_translate("mainWindow", "Edit"))
        self.buttonClear.setText(_translate("mainWindow", "Clear"))
        self.buttonHapus.setText(_translate("mainWindow", "Hapus"))

# kemudian dipanggil
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
